# CS559 - F20 Project #1

## Task Desciption
You are provided with an anonymized dataset containing numeric feature variables, the binary target column, and a string ID_code column.

The task is to predict the value of `target` column in the test set using either **Logistic Regression** and **SVM**. You are welcome to use **regularizaiton**. 

## File descriptions
- train.csv - the training set (202 columns)

- test.csv - the test set. The test set contains some rows which are not included in scoring.

## Rules
- The data does not have specific column names. Therefore, you will not know what data is about. 
- However, you still can do classicaition problem without clustering the training set. **No unsupervised learning techniques in this project**. 
- There are 202 columns. This means that the key of high accuracy comes from **EDA** and **feature enegineering**. 
- There are no rules on EDA and Feature Engineering. 
- On your model, make sure you can reduce the columns at the most of 25%. If we use all columns, we may have high computational cost and getting into bias-variance tradeoff and underfit vs. overfit situations. 
- The project is out of 100. 
    - 50 points will come from your EDA and any pre-processing work. 
    - 30 points will come from your model: Accuracy + overcoming any ML challenges. 
    - 10 points will come from in-class competition. 
        - Ranking the accuracy with less features. 
    - 10 points will come from a report describing your work flow and model evaluations.
        - must be submitted in different file (e.g., pdf, docx). 
        
## Recommand Before-Preprocessing
- You can split the set from the data distribution. 
- You can make multiple new data frames by randomly selecting columns. 
- You can do similar by rows. 

## Recommand Before-training model
- Make sure to delete features from supportive reasons. 

Proejct DUE: 10/23/2020 Friday 11:59 PM. 




In [2]:
import pandas as pd

df = pd.read_csv('train.csv')
df.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266  ...   4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338  ...   7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155  ...   2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250  ...   4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

In [3]:
test_data = pd.read_csv('test.csv',)
test_data.drop(labels="ID_code", axis=1, inplace=True)
test_data.head()

var_0    var_1    var_2   var_3    var_4   var_5   var_6    var_7  \
0  11.0656   7.7798  12.9536  9.4292  11.4327 -2.3805  5.8493  18.2675   
1   8.5304   1.2543  11.3047  5.1858   9.1974 -4.0117  6.0196  18.6316   
2   5.4827 -10.3581  10.1407  7.0479  10.2628  9.8052  4.8950  20.2537   
3   8.5374  -1.3222  12.0220  6.5749   8.8458  3.1744  4.9397  20.5660   
4  11.7058  -0.1327  14.1295  7.7506   9.1035 -8.5848  6.8595  10.6048   

    var_8   var_9  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  2.1337  8.8100  ...  -2.1556  11.8495  -1.4300   2.4508  13.7112   2.4669   
1 -4.4131  5.9739  ...  10.6165   8.8349   0.9403  10.1282  15.5765   0.4773   
2  1.5233  8.3442  ...  -0.7484  10.9935   1.9803   2.1800  12.9813   2.1281   
3  3.3755  7.4578  ...   9.5702   9.0766   1.6580   3.5813  15.1874   3.1656   
4  2.9890  7.1437  ...   4.2259   9.1723   1.2835   3.3778  19.5542  -0.2860   

   var_196  var_197  var_198  var_199  
0   4.3654  10.7200  15.4722  -8.7197  
1  -1.4852   9.8714  19.1293 -20.9760  
2  -7.1086   7.0618  19.8956 -23.1794  
3   3.9567   9.2295  13.0168  -4.2108  
4  -5.1612   7.2882  13.9260  -9.1846  

[5 rows x 200 columns]

In [4]:
df['target'].value_counts()

0    179902
1     20098
Name: target, dtype: int64

In [5]:
#normalize data between 0 &1
x = df.iloc[:,2:].values
y = df.iloc[:,1].values
dfr=((x-x.min())/(x.max()-x.min()))*1


In [6]:
#feature extraction
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

test = SelectKBest(score_func=f_classif, k=150)
fit = test.fit(dfr,y)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dfr,y, train_size=.8, random_state=42)
X_train1, X_test1, y_train1, y_test1 = train_test_split(x,y, train_size=.8, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()

s.fit_transform(X_train)
s.fit_transform(X_train1)

array([[ 0.53357123, -1.67047693, -0.57711975, ..., -0.80036778,
        -0.98286176,  0.13465476],
       [ 1.55485809,  1.08933341, -0.53895769, ..., -0.47611817,
         2.05104482,  0.461005  ],
       [-0.34230649, -0.74070007, -1.42350658, ...,  0.45688676,
        -0.98505235, -0.58394806],
       ...,
       [ 2.00546841,  0.65097615, -0.18420587, ..., -1.02666926,
        -0.8142192 , -0.70495583],
       [-0.23211415,  2.24198202,  0.82786571, ..., -0.91851366,
         1.82318983,  0.06230493],
       [ 0.30347725, -0.44077922, -0.64825202, ...,  1.79428069,
        -1.15681485,  0.33224683]])

In [12]:
#just a test 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

clf = RandomForestClassifier(random_state=42)

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)


print(100* accuracy_score(y_pred, y_test))


clf.fit(X_train1,y_train1)
y_pred1= clf.predict(X_test1)


print(100* accuracy_score(y_pred1, y_test1))

/Users/isabellalfairman/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


89.7925
89.7925


In [45]:
print(f1_score(y_true=y_test, y_pred=y_pred))
print(f1_score(y_true=y_test1, y_pred=y_pred1))

0.036510194404931244
0.036510194404931244


In [14]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression(solver = 'lbfgs')
reg.fit(X_train, y_train)

y_pred2=reg.predict(X_test)
print(f1_score(y_true=y_test, y_pred=y_pred2))


0.25783276791059667


/Users/isabellalfairman/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [51]:
s.fit_transform(test_data)

array([[ 0.13398157,  2.32744611,  0.85278996, ...,  1.96282758,
        -0.13194481, -0.52635716],
       [-0.70086986,  0.71242283,  0.22675581, ...,  1.04133974,
         1.08355968, -1.70501041],
       [-1.70448957, -2.16157859, -0.21517745, ..., -2.00958206,
         1.33825359, -1.91690508],
       ...,
       [ 0.32181655,  0.96551038,  0.18981414, ...,  0.30499646,
        -1.35562556, -1.83004692],
       [ 0.9601723 ,  0.27492737,  1.12037979, ..., -0.87363057,
        -2.35838103,  0.29178474],
       [-0.06333737,  0.84921287, -0.18214635, ...,  1.54779971,
        -0.51024652, -0.4291995 ]])

In [70]:
test_fit = reg.predict(test_data)

In [63]:
import numpy as np
unique_elements, counts_elements = np.unique(test_fit, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Frequency of unique values of the said array:
[[     0]
 [200000]]


In [69]:
test_targ = pd.read_csv("test_target.csv")
test_targ['target'].value_counts()

0    200000
Name: target, dtype: int64